name: zenodraft
on:
  workflow_dispatch:
  release:
    types:
      - published 

jobs:

  publish:
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v2      
        - name: Create a draft snapshot
          env:
            ZENODO_SANDBOX_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}
          uses: zenodraft/action@8-upserting-octokit
          with:
            publish: false
            sandbox: true
            upsert-doi: true
            upsert-location: doi
            filenames: README.md

