name: zenodraft
on:
  workflow_dispatch:
  release:
    types:
      - created


jobs:

  publish:
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v2      
        - name: git info
          run: git log --max-count=10 --name-only
        - name: Create a draft snapshot
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            ZENODO_SANDBOX_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}
          uses: zenodraft/action@8-upserting-octokit
          with:
            publish: false
            sandbox: true
            upsert-doi: false
            upsert-location: doi
            filenames: README.md CITATION.cff
